//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: veztra
// ----------------------------------------------------------------------------
pub mod veztra {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for veztra
    pub fn program_id() -> Pubkey {
        pubkey!("Aso25jcqxjZ2X3A1QSV4ZgZkj4B8pw6JNd4jNVcpB7pq")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Cancel
    // ....................................................................

    /// Main instruction struct for Cancel
    pub struct CancelInstruction {
        pub accounts: CancelInstructionAccountMetas,
        pub data: CancelInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Cancel instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelInstructionAccountMetas {
        pub creator: AccountMeta,

        pub stream: AccountMeta,

        pub mint: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub creator_token_account: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Cancel instruction
    #[derive(Debug, Clone)]
    pub struct CancelInstructionAccounts {
        pub creator: Pubkey,

        pub stream: Pubkey,

        pub mint: Pubkey,

        pub escrow_token_account: Pubkey,

        pub creator_token_account: Pubkey,

        pub recipient_token_account: Pubkey,
    }

    impl CancelInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            stream: Pubkey,

            mint: Pubkey,

            escrow_token_account: Pubkey,

            creator_token_account: Pubkey,

            recipient_token_account: Pubkey,
        ) -> Self {
            Self {
                creator,

                stream,

                mint,

                escrow_token_account,

                creator_token_account,

                recipient_token_account,
            }
        }
    }

    /// Instruction data for Cancel
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelInstructionData {}

    impl CancelInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelInstruction
    impl CancelInstruction {
        fn discriminator() -> [u8; 8] {
            [232u8, 219u8, 223u8, 41u8, 219u8, 236u8, 220u8, 190u8]
        }

        pub fn data(data: CancelInstructionData) -> Self {
            Self {
                accounts: CancelInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.creator_token_account =
                AccountMeta::new(accounts.creator_token_account, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.creator_token_account.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateStream
    // ....................................................................

    /// Main instruction struct for CreateStream
    pub struct CreateStreamInstruction {
        pub accounts: CreateStreamInstructionAccountMetas,
        pub data: CreateStreamInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateStream instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateStreamInstructionAccountMetas {
        pub creator: AccountMeta,

        pub recipient: AccountMeta,

        pub mint: AccountMeta,

        pub creator_token_account: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub stream: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateStream instruction
    #[derive(Debug, Clone)]
    pub struct CreateStreamInstructionAccounts {
        pub creator: Pubkey,

        pub recipient: Pubkey,

        pub mint: Pubkey,

        pub creator_token_account: Pubkey,

        pub escrow_token_account: Pubkey,

        pub stream: Pubkey,
    }

    impl CreateStreamInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            recipient: Pubkey,

            mint: Pubkey,

            creator_token_account: Pubkey,

            escrow_token_account: Pubkey,

            stream: Pubkey,
        ) -> Self {
            Self {
                creator,

                recipient,

                mint,

                creator_token_account,

                escrow_token_account,

                stream,
            }
        }
    }

    /// Instruction data for CreateStream
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateStreamInstructionData {
        pub total_amount: u64,

        pub start_time: i64,

        pub end_time: i64,

        pub cliff_time: i64,

        pub seed: u64,
    }

    impl CreateStreamInstructionData {
        pub fn new(
            total_amount: u64,

            start_time: i64,

            end_time: i64,

            cliff_time: i64,

            seed: u64,
        ) -> Self {
            Self {
                total_amount,

                start_time,

                end_time,

                cliff_time,

                seed,
            }
        }
    }

    /// Implementation for CreateStreamInstruction
    impl CreateStreamInstruction {
        fn discriminator() -> [u8; 8] {
            [71u8, 188u8, 111u8, 127u8, 108u8, 40u8, 229u8, 158u8]
        }

        pub fn data(data: CreateStreamInstructionData) -> Self {
            Self {
                accounts: CreateStreamInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateStreamInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.recipient = AccountMeta::new_readonly(accounts.recipient, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.creator_token_account =
                AccountMeta::new(accounts.creator_token_account, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.creator_token_account.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetMilestone
    // ....................................................................

    /// Main instruction struct for SetMilestone
    pub struct SetMilestoneInstruction {
        pub accounts: SetMilestoneInstructionAccountMetas,
        pub data: SetMilestoneInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetMilestone instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetMilestoneInstructionAccountMetas {
        pub creator: AccountMeta,

        pub stream: AccountMeta,
    }

    /// Account pubkeys for SetMilestone instruction
    #[derive(Debug, Clone)]
    pub struct SetMilestoneInstructionAccounts {
        pub creator: Pubkey,

        pub stream: Pubkey,
    }

    impl SetMilestoneInstructionAccounts {
        pub fn new(creator: Pubkey, stream: Pubkey) -> Self {
            Self { creator, stream }
        }
    }

    /// Instruction data for SetMilestone
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetMilestoneInstructionData {}

    impl SetMilestoneInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SetMilestoneInstruction
    impl SetMilestoneInstruction {
        fn discriminator() -> [u8; 8] {
            [174u8, 213u8, 91u8, 82u8, 156u8, 42u8, 105u8, 3u8]
        }

        pub fn data(data: SetMilestoneInstructionData) -> Self {
            Self {
                accounts: SetMilestoneInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetMilestoneInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.stream.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Withdraw
    // ....................................................................

    /// Main instruction struct for Withdraw
    pub struct WithdrawInstruction {
        pub accounts: WithdrawInstructionAccountMetas,
        pub data: WithdrawInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Withdraw instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawInstructionAccountMetas {
        pub recipient: AccountMeta,

        pub stream: AccountMeta,

        pub mint: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Withdraw instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawInstructionAccounts {
        pub recipient: Pubkey,

        pub stream: Pubkey,

        pub mint: Pubkey,

        pub escrow_token_account: Pubkey,

        pub recipient_token_account: Pubkey,
    }

    impl WithdrawInstructionAccounts {
        pub fn new(
            recipient: Pubkey,

            stream: Pubkey,

            mint: Pubkey,

            escrow_token_account: Pubkey,

            recipient_token_account: Pubkey,
        ) -> Self {
            Self {
                recipient,

                stream,

                mint,

                escrow_token_account,

                recipient_token_account,
            }
        }
    }

    /// Instruction data for Withdraw
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawInstructionData {}

    impl WithdrawInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for WithdrawInstruction
    impl WithdrawInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 18u8, 70u8, 156u8, 148u8, 109u8, 161u8, 34u8]
        }

        pub fn data(data: WithdrawInstructionData) -> Self {
            Self {
                accounts: WithdrawInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawInstructionAccounts) -> Self {
            self.accounts.recipient = AccountMeta::new(accounts.recipient, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: blockbite
// ----------------------------------------------------------------------------
pub mod blockbite {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for blockbite
    pub fn program_id() -> Pubkey {
        pubkey!("9UipodjT55vBd8zZmEPvcFc8dVCveV1CMzYW2zsDHceX")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Cancel
    // ....................................................................

    /// Main instruction struct for Cancel
    pub struct CancelInstruction {
        pub accounts: CancelInstructionAccountMetas,
        pub data: CancelInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Cancel instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelInstructionAccountMetas {
        pub creator: AccountMeta,

        pub stream: AccountMeta,

        pub mint: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub creator_token_account: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Cancel instruction
    #[derive(Debug, Clone)]
    pub struct CancelInstructionAccounts {
        pub creator: Pubkey,

        pub stream: Pubkey,

        pub mint: Pubkey,

        pub escrow_token_account: Pubkey,

        pub creator_token_account: Pubkey,

        pub recipient_token_account: Pubkey,
    }

    impl CancelInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            stream: Pubkey,

            mint: Pubkey,

            escrow_token_account: Pubkey,

            creator_token_account: Pubkey,

            recipient_token_account: Pubkey,
        ) -> Self {
            Self {
                creator,

                stream,

                mint,

                escrow_token_account,

                creator_token_account,

                recipient_token_account,
            }
        }
    }

    /// Instruction data for Cancel
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelInstructionData {}

    impl CancelInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelInstruction
    impl CancelInstruction {
        fn discriminator() -> [u8; 8] {
            [232u8, 219u8, 223u8, 41u8, 219u8, 236u8, 220u8, 190u8]
        }

        pub fn data(data: CancelInstructionData) -> Self {
            Self {
                accounts: CancelInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.creator_token_account =
                AccountMeta::new(accounts.creator_token_account, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.creator_token_account.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ClaimMilestone
    // ....................................................................

    /// Main instruction struct for ClaimMilestone
    pub struct ClaimMilestoneInstruction {
        pub accounts: ClaimMilestoneInstructionAccountMetas,
        pub data: ClaimMilestoneInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimMilestone instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimMilestoneInstructionAccountMetas {
        pub recipient: AccountMeta,

        pub milestone: AccountMeta,

        pub campaign: AccountMeta,

        pub mint: AccountMeta,

        pub campaign_escrow: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ClaimMilestone instruction
    #[derive(Debug, Clone)]
    pub struct ClaimMilestoneInstructionAccounts {
        pub recipient: Pubkey,

        pub milestone: Pubkey,

        pub campaign: Pubkey,

        pub mint: Pubkey,

        pub campaign_escrow: Pubkey,

        pub recipient_token_account: Pubkey,
    }

    impl ClaimMilestoneInstructionAccounts {
        pub fn new(
            recipient: Pubkey,

            milestone: Pubkey,

            campaign: Pubkey,

            mint: Pubkey,

            campaign_escrow: Pubkey,

            recipient_token_account: Pubkey,
        ) -> Self {
            Self {
                recipient,

                milestone,

                campaign,

                mint,

                campaign_escrow,

                recipient_token_account,
            }
        }
    }

    /// Instruction data for ClaimMilestone
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimMilestoneInstructionData {
        pub milestone_seed: u64,

        pub campaign_seed: u64,
    }

    impl ClaimMilestoneInstructionData {
        pub fn new(milestone_seed: u64, campaign_seed: u64) -> Self {
            Self {
                milestone_seed,

                campaign_seed,
            }
        }
    }

    /// Implementation for ClaimMilestoneInstruction
    impl ClaimMilestoneInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 134u8, 152u8, 37u8, 3u8, 82u8, 214u8, 189u8]
        }

        pub fn data(data: ClaimMilestoneInstructionData) -> Self {
            Self {
                accounts: ClaimMilestoneInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimMilestoneInstructionAccounts) -> Self {
            self.accounts.recipient = AccountMeta::new(accounts.recipient, true);

            self.accounts.milestone = AccountMeta::new(accounts.milestone, false);

            self.accounts.campaign = AccountMeta::new_readonly(accounts.campaign, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.campaign_escrow = AccountMeta::new(accounts.campaign_escrow, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.milestone.clone());

            metas.push(self.accounts.campaign.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.campaign_escrow.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateCampaign
    // ....................................................................

    /// Main instruction struct for CreateCampaign
    pub struct CreateCampaignInstruction {
        pub accounts: CreateCampaignInstructionAccountMetas,
        pub data: CreateCampaignInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateCampaign instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateCampaignInstructionAccountMetas {
        pub founder: AccountMeta,

        pub mint: AccountMeta,

        pub founder_token_account: AccountMeta,

        pub campaign_escrow: AccountMeta,

        pub campaign: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateCampaign instruction
    #[derive(Debug, Clone)]
    pub struct CreateCampaignInstructionAccounts {
        pub founder: Pubkey,

        pub mint: Pubkey,

        pub founder_token_account: Pubkey,

        pub campaign_escrow: Pubkey,

        pub campaign: Pubkey,
    }

    impl CreateCampaignInstructionAccounts {
        pub fn new(
            founder: Pubkey,

            mint: Pubkey,

            founder_token_account: Pubkey,

            campaign_escrow: Pubkey,

            campaign: Pubkey,
        ) -> Self {
            Self {
                founder,

                mint,

                founder_token_account,

                campaign_escrow,

                campaign,
            }
        }
    }

    /// Instruction data for CreateCampaign
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateCampaignInstructionData {
        pub title_hash: [u8; 32],

        pub total_budget: u64,

        pub seed: u64,
    }

    impl CreateCampaignInstructionData {
        pub fn new(title_hash: [u8; 32], total_budget: u64, seed: u64) -> Self {
            Self {
                title_hash,

                total_budget,

                seed,
            }
        }
    }

    /// Implementation for CreateCampaignInstruction
    impl CreateCampaignInstruction {
        fn discriminator() -> [u8; 8] {
            [111u8, 131u8, 187u8, 98u8, 160u8, 193u8, 114u8, 244u8]
        }

        pub fn data(data: CreateCampaignInstructionData) -> Self {
            Self {
                accounts: CreateCampaignInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateCampaignInstructionAccounts) -> Self {
            self.accounts.founder = AccountMeta::new(accounts.founder, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.founder_token_account =
                AccountMeta::new(accounts.founder_token_account, false);

            self.accounts.campaign_escrow = AccountMeta::new(accounts.campaign_escrow, false);

            self.accounts.campaign = AccountMeta::new(accounts.campaign, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.founder.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.founder_token_account.clone());

            metas.push(self.accounts.campaign_escrow.clone());

            metas.push(self.accounts.campaign.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateMilestone
    // ....................................................................

    /// Main instruction struct for CreateMilestone
    pub struct CreateMilestoneInstruction {
        pub accounts: CreateMilestoneInstructionAccountMetas,
        pub data: CreateMilestoneInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateMilestone instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateMilestoneInstructionAccountMetas {
        pub founder: AccountMeta,

        pub campaign: AccountMeta,

        pub milestone: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateMilestone instruction
    #[derive(Debug, Clone)]
    pub struct CreateMilestoneInstructionAccounts {
        pub founder: Pubkey,

        pub campaign: Pubkey,

        pub milestone: Pubkey,
    }

    impl CreateMilestoneInstructionAccounts {
        pub fn new(founder: Pubkey, campaign: Pubkey, milestone: Pubkey) -> Self {
            Self {
                founder,

                campaign,

                milestone,
            }
        }
    }

    /// Instruction data for CreateMilestone
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateMilestoneInstructionData {
        pub description_hash: [u8; 32],

        pub campaign_seed: u64,

        pub milestone_seed: u64,

        pub token_amount: u64,

        pub game_program_id: Pubkey,

        pub recipient: Pubkey,
    }

    impl CreateMilestoneInstructionData {
        pub fn new(
            description_hash: [u8; 32],

            campaign_seed: u64,

            milestone_seed: u64,

            token_amount: u64,

            game_program_id: Pubkey,

            recipient: Pubkey,
        ) -> Self {
            Self {
                description_hash,

                campaign_seed,

                milestone_seed,

                token_amount,

                game_program_id,

                recipient,
            }
        }
    }

    /// Implementation for CreateMilestoneInstruction
    impl CreateMilestoneInstruction {
        fn discriminator() -> [u8; 8] {
            [239u8, 58u8, 201u8, 28u8, 40u8, 186u8, 173u8, 48u8]
        }

        pub fn data(data: CreateMilestoneInstructionData) -> Self {
            Self {
                accounts: CreateMilestoneInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateMilestoneInstructionAccounts) -> Self {
            self.accounts.founder = AccountMeta::new(accounts.founder, true);

            self.accounts.campaign = AccountMeta::new(accounts.campaign, false);

            self.accounts.milestone = AccountMeta::new(accounts.milestone, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.founder.clone());

            metas.push(self.accounts.campaign.clone());

            metas.push(self.accounts.milestone.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateStream
    // ....................................................................

    /// Main instruction struct for CreateStream
    pub struct CreateStreamInstruction {
        pub accounts: CreateStreamInstructionAccountMetas,
        pub data: CreateStreamInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateStream instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateStreamInstructionAccountMetas {
        pub creator: AccountMeta,

        pub recipient: AccountMeta,

        pub mint: AccountMeta,

        pub creator_token_account: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub stream: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateStream instruction
    #[derive(Debug, Clone)]
    pub struct CreateStreamInstructionAccounts {
        pub creator: Pubkey,

        pub recipient: Pubkey,

        pub mint: Pubkey,

        pub creator_token_account: Pubkey,

        pub escrow_token_account: Pubkey,

        pub stream: Pubkey,
    }

    impl CreateStreamInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            recipient: Pubkey,

            mint: Pubkey,

            creator_token_account: Pubkey,

            escrow_token_account: Pubkey,

            stream: Pubkey,
        ) -> Self {
            Self {
                creator,

                recipient,

                mint,

                creator_token_account,

                escrow_token_account,

                stream,
            }
        }
    }

    /// Instruction data for CreateStream
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateStreamInstructionData {
        pub total_amount: u64,

        pub start_time: i64,

        pub end_time: i64,

        pub cliff_time: i64,

        pub seed: u64,

        pub milestone_enabled: bool,
    }

    impl CreateStreamInstructionData {
        pub fn new(
            total_amount: u64,

            start_time: i64,

            end_time: i64,

            cliff_time: i64,

            seed: u64,

            milestone_enabled: bool,
        ) -> Self {
            Self {
                total_amount,

                start_time,

                end_time,

                cliff_time,

                seed,

                milestone_enabled,
            }
        }
    }

    /// Implementation for CreateStreamInstruction
    impl CreateStreamInstruction {
        fn discriminator() -> [u8; 8] {
            [71u8, 188u8, 111u8, 127u8, 108u8, 40u8, 229u8, 158u8]
        }

        pub fn data(data: CreateStreamInstructionData) -> Self {
            Self {
                accounts: CreateStreamInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateStreamInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.recipient = AccountMeta::new_readonly(accounts.recipient, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.creator_token_account =
                AccountMeta::new(accounts.creator_token_account, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.creator_token_account.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetMilestone
    // ....................................................................

    /// Main instruction struct for SetMilestone
    pub struct SetMilestoneInstruction {
        pub accounts: SetMilestoneInstructionAccountMetas,
        pub data: SetMilestoneInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetMilestone instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetMilestoneInstructionAccountMetas {
        pub creator: AccountMeta,

        pub stream: AccountMeta,
    }

    /// Account pubkeys for SetMilestone instruction
    #[derive(Debug, Clone)]
    pub struct SetMilestoneInstructionAccounts {
        pub creator: Pubkey,

        pub stream: Pubkey,
    }

    impl SetMilestoneInstructionAccounts {
        pub fn new(creator: Pubkey, stream: Pubkey) -> Self {
            Self { creator, stream }
        }
    }

    /// Instruction data for SetMilestone
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetMilestoneInstructionData {}

    impl SetMilestoneInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SetMilestoneInstruction
    impl SetMilestoneInstruction {
        fn discriminator() -> [u8; 8] {
            [174u8, 213u8, 91u8, 82u8, 156u8, 42u8, 105u8, 3u8]
        }

        pub fn data(data: SetMilestoneInstructionData) -> Self {
            Self {
                accounts: SetMilestoneInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetMilestoneInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.stream.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SubmitProof
    // ....................................................................

    /// Main instruction struct for SubmitProof
    pub struct SubmitProofInstruction {
        pub accounts: SubmitProofInstructionAccountMetas,
        pub data: SubmitProofInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SubmitProof instruction
    #[derive(Debug, Clone, Default)]
    pub struct SubmitProofInstructionAccountMetas {
        pub recipient: AccountMeta,

        pub campaign: AccountMeta,

        pub milestone: AccountMeta,
    }

    /// Account pubkeys for SubmitProof instruction
    #[derive(Debug, Clone)]
    pub struct SubmitProofInstructionAccounts {
        pub recipient: Pubkey,

        pub campaign: Pubkey,

        pub milestone: Pubkey,
    }

    impl SubmitProofInstructionAccounts {
        pub fn new(recipient: Pubkey, campaign: Pubkey, milestone: Pubkey) -> Self {
            Self {
                recipient,

                campaign,

                milestone,
            }
        }
    }

    /// Instruction data for SubmitProof
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SubmitProofInstructionData {
        pub milestone_seed: u64,

        pub proof_hash: [u8; 32],
    }

    impl SubmitProofInstructionData {
        pub fn new(milestone_seed: u64, proof_hash: [u8; 32]) -> Self {
            Self { milestone_seed, proof_hash }
        }
    }

    /// Implementation for SubmitProofInstruction
    impl SubmitProofInstruction {
        fn discriminator() -> [u8; 8] {
            [54u8, 241u8, 46u8, 84u8, 4u8, 212u8, 46u8, 94u8]
        }

        pub fn data(data: SubmitProofInstructionData) -> Self {
            Self {
                accounts: SubmitProofInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SubmitProofInstructionAccounts) -> Self {
            self.accounts.recipient = AccountMeta::new(accounts.recipient, true);

            self.accounts.campaign = AccountMeta::new_readonly(accounts.campaign, false);

            self.accounts.milestone = AccountMeta::new(accounts.milestone, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.campaign.clone());

            metas.push(self.accounts.milestone.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: VerifyGame
    // ....................................................................

    /// Main instruction struct for VerifyGame
    pub struct VerifyGameInstruction {
        pub accounts: VerifyGameInstructionAccountMetas,
        pub data: VerifyGameInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for VerifyGame instruction
    #[derive(Debug, Clone, Default)]
    pub struct VerifyGameInstructionAccountMetas {
        pub campaign: AccountMeta,

        pub milestone: AccountMeta,

        pub game_program: AccountMeta,
    }

    /// Account pubkeys for VerifyGame instruction
    #[derive(Debug, Clone)]
    pub struct VerifyGameInstructionAccounts {
        pub campaign: Pubkey,

        pub milestone: Pubkey,

        pub game_program: Pubkey,
    }

    impl VerifyGameInstructionAccounts {
        pub fn new(campaign: Pubkey, milestone: Pubkey, game_program: Pubkey) -> Self {
            Self {
                campaign,

                milestone,

                game_program,
            }
        }
    }

    /// Instruction data for VerifyGame
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct VerifyGameInstructionData {
        pub milestone_seed: u64,

        pub session_result_hash: [u8; 32],
    }

    impl VerifyGameInstructionData {
        pub fn new(milestone_seed: u64, session_result_hash: [u8; 32]) -> Self {
            Self { milestone_seed, session_result_hash }
        }
    }

    /// Implementation for VerifyGameInstruction
    impl VerifyGameInstruction {
        fn discriminator() -> [u8; 8] {
            [81u8, 26u8, 37u8, 190u8, 207u8, 209u8, 205u8, 211u8]
        }

        pub fn data(data: VerifyGameInstructionData) -> Self {
            Self {
                accounts: VerifyGameInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: VerifyGameInstructionAccounts) -> Self {
            self.accounts.campaign = AccountMeta::new_readonly(accounts.campaign, false);

            self.accounts.milestone = AccountMeta::new(accounts.milestone, false);

            self.accounts.game_program = AccountMeta::new_readonly(accounts.game_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.campaign.clone());

            metas.push(self.accounts.milestone.clone());

            metas.push(self.accounts.game_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }


    // ....................................................................
    // Instruction: Withdraw
    // ....................................................................

    /// Main instruction struct for Withdraw
    pub struct WithdrawInstruction {
        pub accounts: WithdrawInstructionAccountMetas,
        pub data: WithdrawInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Withdraw instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawInstructionAccountMetas {
        pub recipient: AccountMeta,

        pub stream: AccountMeta,

        pub mint: AccountMeta,

        pub escrow_token_account: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Withdraw instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawInstructionAccounts {
        pub recipient: Pubkey,

        pub stream: Pubkey,

        pub mint: Pubkey,

        pub escrow_token_account: Pubkey,

        pub recipient_token_account: Pubkey,
    }

    impl WithdrawInstructionAccounts {
        pub fn new(
            recipient: Pubkey,

            stream: Pubkey,

            mint: Pubkey,

            escrow_token_account: Pubkey,

            recipient_token_account: Pubkey,
        ) -> Self {
            Self {
                recipient,

                stream,

                mint,

                escrow_token_account,

                recipient_token_account,
            }
        }
    }

    /// Instruction data for Withdraw
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawInstructionData {}

    impl WithdrawInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for WithdrawInstruction
    impl WithdrawInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 18u8, 70u8, 156u8, 148u8, 109u8, 161u8, 34u8]
        }

        pub fn data(data: WithdrawInstructionData) -> Self {
            Self {
                accounts: WithdrawInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawInstructionAccounts) -> Self {
            self.accounts.recipient = AccountMeta::new(accounts.recipient, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.escrow_token_account =
                AccountMeta::new(accounts.escrow_token_account, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.escrow_token_account.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: StreamAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StreamAccount {
    pub creator: Pubkey,

    pub recipient: Pubkey,

    pub mint: Pubkey,

    pub escrow_token_account: Pubkey,

    pub total_amount: u64,

    pub amount_withdrawn: u64,

    pub start_time: i64,

    pub end_time: i64,

    pub cliff_time: i64,

    pub is_cancelled: bool,

    pub bump: u8,

    pub seed: u64,

    pub milestone_reached: bool,

    pub milestone_enabled: bool,
}

impl StreamAccount {
    pub fn new(
        creator: Pubkey,

        recipient: Pubkey,

        mint: Pubkey,

        escrow_token_account: Pubkey,

        total_amount: u64,

        amount_withdrawn: u64,

        start_time: i64,

        end_time: i64,

        cliff_time: i64,

        is_cancelled: bool,

        bump: u8,

        seed: u64,

        milestone_reached: bool,

        milestone_enabled: bool,
    ) -> Self {
        Self {
            creator,

            recipient,

            mint,

            escrow_token_account,

            total_amount,

            amount_withdrawn,

            start_time,

            end_time,

            cliff_time,

            is_cancelled,

            bump,

            seed,

            milestone_reached,

            milestone_enabled,
        }
    }
}

/// Custom struct: CampaignAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CampaignAccount {
    pub founder: Pubkey,

    pub title_hash: [u8; 32],

    pub total_budget: u64,

    pub allocated_amount: u64,

    pub milestone_count: u8,

    pub bump: u8,
}

impl CampaignAccount {
    pub fn new(
        founder: Pubkey,

        title_hash: [u8; 32],

        total_budget: u64,

        allocated_amount: u64,

        milestone_count: u8,

        bump: u8,
    ) -> Self {
        Self {
            founder,

            title_hash,

            total_budget,

            allocated_amount,

            milestone_count,

            bump,
        }
    }
}

/// Custom struct: MilestoneAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MilestoneAccount {
    pub campaign: Pubkey,

    pub recipient: Pubkey,

    pub description_hash: [u8; 32],

    pub game_program_id: Pubkey,

    pub token_amount: u64,

    pub is_verified: bool,

    pub proof_hash: [u8; 32],

    pub proof_submitted: bool,

    pub is_claimed: bool,

    pub bump: u8,
}

impl MilestoneAccount {
    pub fn new(
        campaign: Pubkey,

        recipient: Pubkey,

        description_hash: [u8; 32],

        game_program_id: Pubkey,

        token_amount: u64,

        is_verified: bool,

        proof_hash: [u8; 32],

        proof_submitted: bool,

        is_claimed: bool,

        bump: u8,
    ) -> Self {
        Self {
            campaign,

            recipient,

            description_hash,

            game_program_id,

            token_amount,

            is_verified,

            proof_hash,

            proof_submitted,

            is_claimed,

            bump,
        }
    }
}


// ============================================================================
// END OF GENERATED FILE
// ============================================================================
