[features]
resolution = true
skip-lint = false

[programs.localnet]
blockbite_vesting = "Fg6PaFpoGXkYsidMpWxTWqzXY6vSAQ6sMmBm4o9mpU3"

[programs.devnet]
blockbite_vesting = "Fg6PaFpoGXkYsidMpWxTWqzXY6vSAQ6sMmBm4o9mpU3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.anchor.json -t 1000000 tests/**/*.ts"
