[fuzz]
enabled = true


[[fuzz.programs]]
address = "9UipodjT55vBd8zZmEPvcFc8dVCveV1CMzYW2zsDHceX"
program = ".target/deploy/blockbite.so"


[[fuzz.targets]]
name = "fuzz_0"
path = "trident-tests/fuzz_0"
