/**
 * Week 4 — Token Locking + Linear Vesting
 * Full unit test suite: all acceptance criteria + cliff + VGPV field verification.
 *
 * Run with:  anchor test
 * (NOT yarn test:anchor — Anchor CLI auto-builds the IDL first)
 */

import * as anchor from "@coral-xyz/anchor";
import { Program, BN } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  SYSVAR_RENT_PUBKEY,
} from "@solana/web3.js";
import {
  TOKEN_PROGRAM_ID,
  createMint,
  createAssociatedTokenAccount,
  mintTo,
  getAccount,
} from "@solana/spl-token";
import { assert } from "chai";

// IDL is generated by `anchor build` into target/idl/
const IDL = require("../target/idl/blockbite_vesting.json");
const PROGRAM_ID = new PublicKey("GrWHUoeu8STsXh7Dy2gyMmQsaujjTux6qU6BS7119SfH");

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

describe("blockbite-vesting — Week 4 acceptance criteria", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);
  const program = new Program(IDL, PROGRAM_ID, provider);

  let mint: PublicKey;
  let creatorAta: PublicKey;
  let recipientAta: PublicKey;
  let wrongUserAta: PublicKey;

  const creator   = Keypair.generate();
  const recipient = Keypair.generate();
  const wrongUser = Keypair.generate();
  const STREAM_ID = new BN(1);
  const AMOUNT    = new BN(1_000_000); // 1M tokens
  const DURATION  = 100;               // 100 seconds for test speed

  async function deriveStreamPDA(authority: PublicKey, streamId: BN) {
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("stream"),
        authority.toBuffer(),
        streamId.toArrayLike(Buffer, "le", 8),
      ],
      PROGRAM_ID
    );
  }

  async function deriveVaultPDA(authority: PublicKey, streamId: BN) {
    return PublicKey.findProgramAddressSync(
      [
        Buffer.from("vault"),
        authority.toBuffer(),
        streamId.toArrayLike(Buffer, "le", 8),
      ],
      PROGRAM_ID
    );
  }

  before(async () => {
    // Airdrop SOL to all keypairs
    for (const kp of [creator, recipient, wrongUser]) {
      const sig = await provider.connection.requestAirdrop(kp.publicKey, 2e9);
      await provider.connection.confirmTransaction(sig, "confirmed");
    }

    // Create SPL mint
    mint = await createMint(provider.connection, creator, creator.publicKey, null, 6);

    // Create ATAs
    creatorAta    = await createAssociatedTokenAccount(provider.connection, creator,    mint, creator.publicKey);
    recipientAta  = await createAssociatedTokenAccount(provider.connection, recipient,  mint, recipient.publicKey);
    wrongUserAta  = await createAssociatedTokenAccount(provider.connection, wrongUser,  mint, wrongUser.publicKey);

    // Mint 20M tokens to creator (enough for all streams)
    await mintTo(provider.connection, creator, mint, creatorAta, creator, 20_000_000);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC1 + AC2: create_stream locks tokens; creator ATA debited
  // ──────────────────────────────────────────────────────────────────────────
  it("AC1+AC2: create_stream deposits tokens into PDA vault", async () => {
    const now     = Math.floor(Date.now() / 1000);
    const startTs = new BN(now);
    const endTs   = new BN(now + DURATION);

    const [streamPDA] = await deriveStreamPDA(creator.publicKey, STREAM_ID);
    const [vaultPDA]  = await deriveVaultPDA(creator.publicKey, STREAM_ID);

    const creatorBefore = await getAccount(provider.connection, creatorAta);

    await program.methods
      .createStream(STREAM_ID, AMOUNT, startTs, new BN(0), endTs)
      .accounts({
        authority:    creator.publicKey,
        beneficiary:  recipient.publicKey,
        mint,
        stream:       streamPDA,
        vault:        vaultPDA,
        authorityAta: creatorAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([creator])
      .rpc();

    const vault = await getAccount(provider.connection, vaultPDA);
    assert.equal(vault.amount.toString(), AMOUNT.toString(), "Vault must hold full amount");

    const creatorAfter = await getAccount(provider.connection, creatorAta);
    assert.equal(
      (BigInt(creatorBefore.amount.toString()) - BigInt(creatorAfter.amount.toString())).toString(),
      AMOUNT.toString(),
      "Creator ATA must be debited"
    );

    const stream = await program.account.streamAccount.fetch(streamPDA);
    assert.equal(stream.amountTotal.toString(), AMOUNT.toString());
    assert.equal(stream.amountWithdrawn.toString(), "0");
    assert.equal(stream.beneficiary.toBase58(), recipient.publicKey.toBase58());
    assert.equal(stream.cancelled, false);
    // VGPV fields initialised
    assert.equal(stream.velocityStrikes, 0, "velocity_strikes must start at 0");

    console.log("  ✓ create_stream: vault funded, stream state correct, VGPV fields initialised");
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC3a: 0% unlocked before start_ts
  // ──────────────────────────────────────────────────────────────────────────
  it("AC3a: unlocked = 0 before start_ts", async () => {
    const futureId = new BN(100);
    const future   = Math.floor(Date.now() / 1000) + 3600; // 1 hr from now
    const [streamPDA] = await deriveStreamPDA(creator.publicKey, futureId);
    const [vaultPDA]  = await deriveVaultPDA(creator.publicKey, futureId);

    await program.methods
      .createStream(futureId, AMOUNT, new BN(future), new BN(0), new BN(future + DURATION))
      .accounts({
        authority:    creator.publicKey,
        beneficiary:  recipient.publicKey,
        mint,
        stream:       streamPDA,
        vault:        vaultPDA,
        authorityAta: creatorAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([creator])
      .rpc();

    const stream = await program.account.streamAccount.fetch(streamPDA);
    const nowSec = Math.floor(Date.now() / 1000);
    assert(nowSec < stream.startTs.toNumber(), "Should be before start");
    console.log("  ✓ AC3a: 0% unlocked before start_ts confirmed via state");
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC3b: ~25% unlocked at 25% of duration
  // ──────────────────────────────────────────────────────────────────────────
  it("AC3b: ~25% unlocked at 25% of duration", async () => {
    const streamId25  = new BN(10);
    const now         = Math.floor(Date.now() / 1000);
    const startTs     = new BN(now - 250); // 250s elapsed of 1000s = 25%
    const endTs       = new BN(now + 750);
    const [streamPDA] = await deriveStreamPDA(creator.publicKey, streamId25);
    const [vaultPDA]  = await deriveVaultPDA(creator.publicKey, streamId25);

    await program.methods
      .createStream(streamId25, AMOUNT, startTs, new BN(0), endTs)
      .accounts({
        authority:    creator.publicKey,
        beneficiary:  recipient.publicKey,
        mint,
        stream:       streamPDA,
        vault:        vaultPDA,
        authorityAta: creatorAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([creator])
      .rpc();

    const recipientBefore = await getAccount(provider.connection, recipientAta);
    await program.methods
      .withdraw()
      .accounts({
        beneficiary:    recipient.publicKey,
        stream:         streamPDA,
        vault:          vaultPDA,
        beneficiaryAta: recipientAta,
        tokenProgram:   TOKEN_PROGRAM_ID,
      })
      .signers([recipient])
      .rpc();

    const recipientAfter = await getAccount(provider.connection, recipientAta);
    const received = Number(
      BigInt(recipientAfter.amount.toString()) - BigInt(recipientBefore.amount.toString())
    );
    const expected25 = AMOUNT.toNumber() * 0.25;
    const tolerance  = AMOUNT.toNumber() * 0.05;
    assert(
      received >= expected25 - tolerance && received <= expected25 + tolerance,
      `Expected ~25% (${expected25}) ± ${tolerance}, got ${received}`
    );
    console.log(`  ✓ AC3b: ~25% unlocked = ${received} tokens (expected ~${expected25})`);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC3d: ~50% unlocked at 50% of duration
  // ──────────────────────────────────────────────────────────────────────────
  it("AC3d: ~50% unlocked at 50% of duration", async () => {
    const streamId50  = new BN(11);
    const now         = Math.floor(Date.now() / 1000);
    const startTs     = new BN(now - 500); // 500s elapsed of 1000s = 50%
    const endTs       = new BN(now + 500);
    const [streamPDA] = await deriveStreamPDA(creator.publicKey, streamId50);
    const [vaultPDA]  = await deriveVaultPDA(creator.publicKey, streamId50);

    await program.methods
      .createStream(streamId50, AMOUNT, startTs, new BN(0), endTs)
      .accounts({
        authority:    creator.publicKey,
        beneficiary:  recipient.publicKey,
        mint,
        stream:       streamPDA,
        vault:        vaultPDA,
        authorityAta: creatorAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([creator])
      .rpc();

    const recipientBefore = await getAccount(provider.connection, recipientAta);
    await program.methods
      .withdraw()
      .accounts({
        beneficiary:    recipient.publicKey,
        stream:         streamPDA,
        vault:          vaultPDA,
        beneficiaryAta: recipientAta,
        tokenProgram:   TOKEN_PROGRAM_ID,
      })
      .signers([recipient])
      .rpc();

    const recipientAfter = await getAccount(provider.connection, recipientAta);
    const received = Number(
      BigInt(recipientAfter.amount.toString()) - BigInt(recipientBefore.amount.toString())
    );
    const expected50 = AMOUNT.toNumber() * 0.50;
    const tolerance  = AMOUNT.toNumber() * 0.05;
    assert(
      received >= expected50 - tolerance && received <= expected50 + tolerance,
      `Expected ~50% (${expected50}) ± ${tolerance}, got ${received}`
    );
    console.log(`  ✓ AC3d: ~50% unlocked = ${received} tokens (expected ~${expected50})`);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC4: withdraw — recipient can claim vested tokens
  // ──────────────────────────────────────────────────────────────────────────
  it("AC4: withdraw transfers vested tokens to recipient", async () => {
    await sleep(12_000); // wait for >10s of the 100s stream to vest

    const [streamPDA] = await deriveStreamPDA(creator.publicKey, STREAM_ID);
    const [vaultPDA]  = await deriveVaultPDA(creator.publicKey, STREAM_ID);

    const recipientBefore = await getAccount(provider.connection, recipientAta);

    await program.methods
      .withdraw()
      .accounts({
        beneficiary:    recipient.publicKey,
        stream:         streamPDA,
        vault:          vaultPDA,
        beneficiaryAta: recipientAta,
        tokenProgram:   TOKEN_PROGRAM_ID,
      })
      .signers([recipient])
      .rpc();

    const recipientAfter = await getAccount(provider.connection, recipientAta);
    const received = BigInt(recipientAfter.amount.toString()) - BigInt(recipientBefore.amount.toString());
    assert(received > 0n, "Recipient must receive tokens");

    const stream = await program.account.streamAccount.fetch(streamPDA);
    assert(stream.amountWithdrawn.gtn(0), "amount_withdrawn must be updated");

    console.log(`  ✓ AC4: withdraw: recipient received ${received} tokens`);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC5: partial withdrawals — claim more after waiting
  // ──────────────────────────────────────────────────────────────────────────
  it("AC5: partial withdrawals work — claim more after waiting", async () => {
    const [streamPDA]     = await deriveStreamPDA(creator.publicKey, STREAM_ID);
    const streamBefore    = await program.account.streamAccount.fetch(streamPDA);
    const withdrawnBefore = streamBefore.amountWithdrawn.toNumber();

    await sleep(10_000);

    const [vaultPDA] = await deriveVaultPDA(creator.publicKey, STREAM_ID);
    await program.methods
      .withdraw()
      .accounts({
        beneficiary:    recipient.publicKey,
        stream:         streamPDA,
        vault:          vaultPDA,
        beneficiaryAta: recipientAta,
        tokenProgram:   TOKEN_PROGRAM_ID,
      })
      .signers([recipient])
      .rpc();

    const streamAfter = await program.account.streamAccount.fetch(streamPDA);
    assert(
      streamAfter.amountWithdrawn.toNumber() > withdrawnBefore,
      "Second withdrawal must increase amount_withdrawn"
    );
    console.log("  ✓ AC5: partial withdrawals work — second claim successful");
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC6: NothingToWithdraw when nothing new has vested
  // ──────────────────────────────────────────────────────────────────────────
  it("AC6: cannot withdraw more than unlocked — NothingToWithdraw error", async () => {
    const [streamPDA] = await deriveStreamPDA(creator.publicKey, STREAM_ID);
    const [vaultPDA]  = await deriveVaultPDA(creator.publicKey, STREAM_ID);

    try {
      await program.methods
        .withdraw()
        .accounts({
          beneficiary:    recipient.publicKey,
          stream:         streamPDA,
          vault:          vaultPDA,
          beneficiaryAta: recipientAta,
          tokenProgram:   TOKEN_PROGRAM_ID,
        })
        .signers([recipient])
        .rpc();
      assert.fail("Should have thrown NothingToWithdraw");
    } catch (e: any) {
      assert(
        e.message.includes("NothingToWithdraw") || e.error?.errorCode?.code === "NothingToWithdraw",
        `Expected NothingToWithdraw, got: ${e.message}`
      );
      console.log("  ✓ AC6: NothingToWithdraw returned correctly");
    }
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC7: Unauthorized — wrong user cannot withdraw
  // ──────────────────────────────────────────────────────────────────────────
  it("AC7: unauthorized user cannot withdraw — Unauthorized error", async () => {
    const streamId2   = new BN(2);
    const now         = Math.floor(Date.now() / 1000);
    const [streamPDA] = await deriveStreamPDA(creator.publicKey, streamId2);
    const [vaultPDA]  = await deriveVaultPDA(creator.publicKey, streamId2);

    await program.methods
      .createStream(streamId2, AMOUNT, new BN(now - 50), new BN(0), new BN(now + 50))
      .accounts({
        authority:    creator.publicKey,
        beneficiary:  recipient.publicKey,
        mint,
        stream:       streamPDA,
        vault:        vaultPDA,
        authorityAta: creatorAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([creator])
      .rpc();

    try {
      await program.methods
        .withdraw()
        .accounts({
          beneficiary:    wrongUser.publicKey,
          stream:         streamPDA,
          vault:          vaultPDA,
          beneficiaryAta: wrongUserAta,
          tokenProgram:   TOKEN_PROGRAM_ID,
        })
        .signers([wrongUser])
        .rpc();
      assert.fail("Should have thrown Unauthorized");
    } catch (e: any) {
      assert(
        e.message.includes("Unauthorized") || e.error?.errorCode?.code === "Unauthorized",
        `Expected Unauthorized, got: ${e.message}`
      );
      console.log("  ✓ AC7: Unauthorized error returned correctly");
    }
  });

  // ──────────────────────────────────────────────────────────────────────────
  // AC3c: 100% unlocked after end_ts
  // ──────────────────────────────────────────────────────────────────────────
  it("AC3c: 100% unlocked after end_ts — full withdrawal succeeds", async () => {
    const streamId3   = new BN(3);
    const now         = Math.floor(Date.now() / 1000);
    const [streamPDA] = await deriveStreamPDA(creator.publicKey, streamId3);
    const [vaultPDA]  = await deriveVaultPDA(creator.publicKey, streamId3);

    await program.methods
      .createStream(streamId3, AMOUNT, new BN(now - 200), new BN(0), new BN(now - 1))
      .accounts({
        authority:    creator.publicKey,
        beneficiary:  recipient.publicKey,
        mint,
        stream:       streamPDA,
        vault:        vaultPDA,
        authorityAta: creatorAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([creator])
      .rpc();

    const recipientBefore = await getAccount(provider.connection, recipientAta);

    await program.methods
      .withdraw()
      .accounts({
        beneficiary:    recipient.publicKey,
        stream:         streamPDA,
        vault:          vaultPDA,
        beneficiaryAta: recipientAta,
        tokenProgram:   TOKEN_PROGRAM_ID,
      })
      .signers([recipient])
      .rpc();

    const recipientAfter = await getAccount(provider.connection, recipientAta);
    const received = BigInt(recipientAfter.amount.toString()) - BigInt(recipientBefore.amount.toString());
    assert.equal(received.toString(), AMOUNT.toString(), "100% must be withdrawable after end_ts");

    const stream = await program.account.streamAccount.fetch(streamPDA);
    assert.equal(stream.amountWithdrawn.toString(), AMOUNT.toString(), "amount_withdrawn must equal amount_total");
    console.log("  ✓ AC3c: 100% withdrawal after end_ts — full amount received");
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Cliff: nothing claimable before cliff_ts even if start_ts has passed
  // ──────────────────────────────────────────────────────────────────────────
  it("Cliff: 0 claimable before cliff_ts; normal vesting after cliff", async () => {
    const streamIdCliff = new BN(20);
    const now           = Math.floor(Date.now() / 1000);
    // Stream started 100s ago; cliff is 1hr in the future → nothing claimable yet
    const startTs = new BN(now - 100);
    const cliffTs = new BN(now + 3600);
    const endTs   = new BN(now + 900);
    const [streamPDA]   = await deriveStreamPDA(creator.publicKey, streamIdCliff);
    const [vaultPDA]    = await deriveVaultPDA(creator.publicKey, streamIdCliff);

    await program.methods
      .createStream(streamIdCliff, AMOUNT, startTs, cliffTs, endTs)
      .accounts({
        authority:    creator.publicKey,
        beneficiary:  recipient.publicKey,
        mint,
        stream:       streamPDA,
        vault:        vaultPDA,
        authorityAta: creatorAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([creator])
      .rpc();

    // Attempt withdraw before cliff — must get NothingToWithdraw
    try {
      await program.methods
        .withdraw()
        .accounts({
          beneficiary:    recipient.publicKey,
          stream:         streamPDA,
          vault:          vaultPDA,
          beneficiaryAta: recipientAta,
          tokenProgram:   TOKEN_PROGRAM_ID,
        })
        .signers([recipient])
        .rpc();
      assert.fail("Should have thrown NothingToWithdraw before cliff");
    } catch (e: any) {
      assert(
        e.message.includes("NothingToWithdraw") || e.error?.errorCode?.code === "NothingToWithdraw",
        `Expected NothingToWithdraw before cliff, got: ${e.message}`
      );
    }

    // Stream with cliff already past → normal vesting works
    const streamIdCliff2  = new BN(21);
    const startTs2 = new BN(now - 500);
    const cliffTs2 = new BN(now - 100); // cliff already 100s ago
    const endTs2   = new BN(now + 500);
    const [streamPDA2] = await deriveStreamPDA(creator.publicKey, streamIdCliff2);
    const [vaultPDA2]  = await deriveVaultPDA(creator.publicKey, streamIdCliff2);

    await program.methods
      .createStream(streamIdCliff2, AMOUNT, startTs2, cliffTs2, endTs2)
      .accounts({
        authority:    creator.publicKey,
        beneficiary:  recipient.publicKey,
        mint,
        stream:       streamPDA2,
        vault:        vaultPDA2,
        authorityAta: creatorAta,
        tokenProgram: TOKEN_PROGRAM_ID,
        systemProgram: SystemProgram.programId,
        rent: SYSVAR_RENT_PUBKEY,
      })
      .signers([creator])
      .rpc();

    const recipientBefore = await getAccount(provider.connection, recipientAta);
    await program.methods
      .withdraw()
      .accounts({
        beneficiary:    recipient.publicKey,
        stream:         streamPDA2,
        vault:          vaultPDA2,
        beneficiaryAta: recipientAta,
        tokenProgram:   TOKEN_PROGRAM_ID,
      })
      .signers([recipient])
      .rpc();

    const recipientAfter = await getAccount(provider.connection, recipientAta);
    const received = Number(
      BigInt(recipientAfter.amount.toString()) - BigInt(recipientBefore.amount.toString())
    );
    assert(received > 0, "Should receive tokens after cliff has passed");
    console.log(`  ✓ Cliff: blocked before cliff_ts; ${received} tokens available after cliff`);
  });

  // ──────────────────────────────────────────────────────────────────────────
  // VGPV: velocity_strikes field is readable and starts at 0
  // ──────────────────────────────────────────────────────────────────────────
  it("VGPV: velocity_strikes and last_action_ts fields exist on StreamAccount", async () => {
    const [streamPDA] = await deriveStreamPDA(creator.publicKey, STREAM_ID);
    const stream = await program.account.streamAccount.fetch(streamPDA);

    assert(typeof stream.velocityStrikes === "number", "velocity_strikes field must exist");
    assert(typeof stream.lastActionTs.toNumber === "function", "last_action_ts field must exist");
    console.log(`  ✓ VGPV: velocityStrikes=${stream.velocityStrikes}, lastActionTs=${stream.lastActionTs.toNumber()}`);
  });
});
